import React, { useState, useEffect } from 'react'
import { Paper, SynthesisData } from '../types'
import { API } from '../config'

interface Props {
  sessionId: string
  synthesis: SynthesisData
  simulationResults: number[]
}

export default function PaperView({ sessionId, synthesis, simulationResults }: Props) {
  const [paper, setPaper] = useState<Paper | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetch(`${API}/session/${sessionId}/paper`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' }
    })
      .then(r => r.json())
      .then(data => { setPaper(data); setLoading(false) })
      .catch(() => setLoading(false))
  }, [])

  const buildText = () =>
    `${paper!.title}\n\n${paper!.authors.join(', ')} · ${paper!.date}\n\nKeywords: ${paper!.keywords.join(', ')}\n\nABSTRACT\n${paper!.abstract}\n\n${paper!.sections.map(s => `${s.title}\n${s.content}`).join('\n\n')}\n\nREFERENCES\n${paper!.references.join('\n')}`

  const copyText = () => {
    if (!paper) return
    navigator.clipboard.writeText(buildText())
  }

  const downloadPaper = () => {
    if (!paper) return
    const blob = new Blob([buildText()], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${paper.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const downloadPDF = () => {
    if (!paper) return
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${paper.title}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Georgia', 'Times New Roman', serif; font-size: 11pt; color: #111; background: #fff; padding: 0; }
    @page { margin: 2.2cm 2.5cm; size: A4; }
    @media print { body { padding: 0; } .no-print { display: none; } }

    .header-label { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 8pt; font-weight: 700; letter-spacing: 2px; color: #1C6EF3; text-transform: uppercase; margin-bottom: 14px; }
    h1 { font-size: 20pt; font-weight: 700; line-height: 1.3; color: #0a0a0f; margin-bottom: 10px; letter-spacing: -0.3px; }
    .meta { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 9pt; color: #666; margin-bottom: 14px; }
    .keywords { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 20px; }
    .keyword { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 8pt; padding: 3px 10px; border-radius: 100px; background: #EEF3FF; color: #1C6EF3; border: 1px solid #C7D9FF; }
    .divider { border: none; border-top: 1px solid #e0e0e0; margin: 20px 0; }
    .abstract-box { background: #F5F8FF; border: 1px solid #C7D9FF; border-radius: 8px; padding: 16px 18px; margin-bottom: 24px; }
    .abstract-label { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 8pt; font-weight: 700; letter-spacing: 1.5px; color: #1C6EF3; margin-bottom: 8px; }
    .abstract-text { font-size: 10.5pt; line-height: 1.7; color: #222; }
    h2 { font-size: 13pt; font-weight: 700; color: #0a0a0f; margin-bottom: 8px; margin-top: 24px; letter-spacing: -0.2px; }
    p { font-size: 11pt; line-height: 1.8; color: #222; margin-bottom: 12px; text-align: justify; }
    .references { margin-top: 28px; padding-top: 18px; border-top: 1px solid #e0e0e0; }
    .ref { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 9pt; color: #555; line-height: 1.6; margin-bottom: 5px; }
    .footer { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 8pt; color: #aaa; text-align: center; margin-top: 32px; padding-top: 12px; border-top: 1px solid #eee; }
    .print-btn { no-print: 1; font-family: 'Helvetica Neue', Arial, sans-serif; background: #1C6EF3; color: #fff; border: none; padding: 10px 24px; border-radius: 8px; font-size: 13px; font-weight: 600; cursor: pointer; display: block; margin: 0 auto 24px; }
  </style>
</head>
<body>
  <button class="print-btn no-print" onclick="window.print()">Save as PDF</button>
  <div class="header-label">DriftOwl · Mechanism Design Intelligence</div>
  <h1>${paper.title}</h1>
  <div class="meta">${paper.authors.join(', ')} &nbsp;·&nbsp; ${paper.date}</div>
  <div class="keywords">${paper.keywords.map(k => `<span class="keyword">${k}</span>`).join('')}</div>
  <hr class="divider">
  <div class="abstract-box">
    <div class="abstract-label">Abstract</div>
    <div class="abstract-text">${paper.abstract}</div>
  </div>
  ${paper.sections.map(s => `<h2>${s.title}</h2><p>${s.content.replace(/\n/g, '</p><p>')}</p>`).join('\n')}
  <div class="references">
    <h2>References</h2>
    ${paper.references.map(r => `<div class="ref">${r}</div>`).join('\n')}
  </div>
  <div class="footer">Generated by DriftOwl · driftowl.ai</div>
  <script>window.onload = () => setTimeout(() => window.print(), 400)</script>
</body>
</html>`

    const win = window.open('', '_blank')
    if (!win) return
    win.document.write(html)
    win.document.close()
  }

  if (loading) return (
    <div style={{
      height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center',
      flexDirection: 'column', gap: 16
    }}>
      <div style={{
        width: 32, height: 32, border: '2px solid rgba(0,0,0,0.08)',
        borderTop: '2px solid #1C6EF3', borderRadius: '50%', animation: 'spin 0.8s linear infinite'
      }} />
      <span style={{ fontSize: 15, color: '#8A8A8E' }}>Writing research paper...</span>
    </div>
  )

  if (!paper) return (
    <div style={{ height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <span style={{ color: '#8A8A8E' }}>Failed to generate paper.</span>
    </div>
  )

  return (
    <div style={{ height: '100%', overflowY: 'auto', padding: '32px 40px', maxWidth: 760, margin: '0 auto' }}>
      {/* Paper header */}
      <div style={{ marginBottom: 32, paddingBottom: 24, borderBottom: '1px solid rgba(0,0,0,0.08)' }}>
        <div style={{
          fontSize: 11, fontWeight: 600, letterSpacing: 1.5, color: '#1C6EF3',
          marginBottom: 12, textTransform: 'uppercase'
        }}>
          DriftOwl Research · Mechanism Design Study
        </div>
        <h1 style={{ fontSize: 24, fontWeight: 700, color: '#0A0A0F', lineHeight: 1.3, marginBottom: 12, letterSpacing: -0.5 }}>
          {paper.title}
        </h1>
        <div style={{ fontSize: 13, color: '#8A8A8E', marginBottom: 16 }}>
          {paper.authors.join(', ')} · {paper.date}
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 16 }}>
          {paper.keywords.map(k => (
            <span key={k} style={{
              fontSize: 11, padding: '3px 10px', borderRadius: 100,
              background: 'rgba(28,110,243,0.08)', color: '#1C6EF3',
              border: '1px solid rgba(28,110,243,0.15)'
            }}>{k}</span>
          ))}
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <button onClick={copyText} style={{
            padding: '8px 16px', borderRadius: 10, border: '1px solid rgba(0,0,0,0.1)',
            background: 'rgba(255,255,255,0.8)', fontSize: 13, color: '#0A0A0F',
            cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6
          }}>
            📋 Copy full text
          </button>
          <button onClick={downloadPaper} style={{
            padding: '8px 16px', borderRadius: 10, border: '1px solid rgba(0,0,0,0.1)',
            background: 'rgba(255,255,255,0.8)', fontSize: 13, color: '#0A0A0F',
            cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6
          }}>
            ⬇️ Download .txt
          </button>
          <button onClick={downloadPDF} style={{
            padding: '8px 16px', borderRadius: 10, border: '1px solid rgba(28,110,243,0.3)',
            background: 'rgba(28,110,243,0.06)', fontSize: 13, color: '#1C6EF3',
            cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6, fontWeight: 600
          }}>
            ⬇️ Download PDF
          </button>
        </div>
      </div>

      {/* Abstract */}
      <div style={{
        background: 'rgba(28,110,243,0.04)', border: '1px solid rgba(28,110,243,0.1)',
        borderRadius: 16, padding: 20, marginBottom: 28
      }}>
        <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: 1, color: '#1C6EF3', marginBottom: 8 }}>ABSTRACT</div>
        <p style={{ fontSize: 14, color: '#3C3C43', lineHeight: 1.7, margin: 0 }}>{paper.abstract}</p>
      </div>

      {/* Sections */}
      {paper.sections.map((section, i) => (
        <div key={i} style={{ marginBottom: 28 }}>
          <h2 style={{ fontSize: 17, fontWeight: 700, color: '#0A0A0F', marginBottom: 10, letterSpacing: -0.3 }}>
            {section.title}
          </h2>
          <p style={{ fontSize: 14, color: '#3C3C43', lineHeight: 1.8, margin: 0 }}>
            {section.content}
          </p>
        </div>
      ))}

      {/* References */}
      <div style={{ marginTop: 32, paddingTop: 24, borderTop: '1px solid rgba(0,0,0,0.08)' }}>
        <h2 style={{ fontSize: 17, fontWeight: 700, color: '#0A0A0F', marginBottom: 12, letterSpacing: -0.3 }}>
          References
        </h2>
        {paper.references.map((ref, i) => (
          <p key={i} style={{ fontSize: 13, color: '#6E6E73', lineHeight: 1.6, marginBottom: 6 }}>
            {ref}
          </p>
        ))}
      </div>
    </div>
  )
}
